# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: KnitStore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # Use the latest Windows runner

    env:
      Solution_Name: Backend/Ecommerce.sln  # Your .NET solution file
      Configuration: ${{ matrix.configuration }}  # Configuration (Debug/Release)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Make sure to fetch all branches and tags

    # Install .NET SDK (dotnet SDK for building .NET Core/.NET 5+ projects)
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x  # Adjust this to match the version your app is using (e.g., 6.0, 7.0)

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }} --configuration ${{ env.Configuration }}

    # Build the solution
    - name: Build the solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ env.Configuration }} --no-restore

    # Optionally, run tests (if you have any unit tests defined)
    # - name: Run tests
    #   run: dotnet test ${{ env.Solution_Name }} --configuration ${{ env.Configuration }}

    # Publish the application (if you want to create a deployment package)
    - name: Publish the application
      run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ env.Configuration }} --output ./publish

    # Upload build artifacts (if you need to store the build output)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: .NET Build Output
        path: ./publish  # The output folder where the publish step created files
